env:
  matrix:
  - VERSION=0.0.1
  global:
    secure: pKUasEwqsUIsLHhI73rIOCpxtT3DHe0VjYeWTEWlEAx7qBogZoPfLNIgKFEPdo2szyNxJyo0SfYxl24FsSzuM17cBelPFbnHYBWA4yzZTAe4qeihbTiLR8kBE4FuuEwdHJDUiM7/4/uAXanD95tGPP2R5ssgmw9v69SlZ2bN1Rl/bqxocjqhXb43WE9/ooiLn3iVom+tcXc5+1s1RrByxpvLC4fTcDzjNNFrcQompmciZEmY95qdsSNHPPPcI71B23Tise7uyRayJObn45GLXvHMlbISzJR49B9/BNhQJAaGElaF4hi4+CBRXkzYMcvvVO4jwlvDg2i2NpYTIzULe5hJbviPIf0XiZHAmxh6pTgveJO7dM+QLJbjPsGCS/K49GlhJiM+5s7P1G6jGLyFpwkeJD7CjAauJzeWrmwB5ExejnwFFfPtC3PMytOJkOZuik3NdxRdtUfnS/eWOrQ5K9d5nw8k25zuRgha4OsXHLog5RYVvTAYQZPk098aUkYuQuq2BAAlqxm5NrXXLxXfCgThEahaSRNvnCYoQjBK8L+52ImL+iMTmjukvUmiEuIAX70KRoFGjzgLJpIJY3PAgAUh7sqH8goxzC2CbrpbFas4rndDTu5AIvKUYx1hWqA0Fw4XCX5rk2F7vFaz13rG2sfpT9ZhayEkRc5T2HDMaRY=

services:
- docker

script:
- docker build --build-arg VERSION="${VERSION}" -t temp-build .
- docker run --rm temp-build --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
